{"uuid": "243147f8-6598-49cf-b918-1b13e5328861", "children": ["f7e12847-d6a6-4eb9-ad5f-ad6940e21a27"], "befores": [{"name": "setup_login", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=131.0.6778.86)\nStacktrace:\n\tGetHandleVerifier [0x00D033E3+25059]\n\t(No symbol) [0x00C8CDE4]\n\t(No symbol) [0x00B6BEC3]\n\t(No symbol) [0x00B4D93B]\n\t(No symbol) [0x00BD800F]\n\t(No symbol) [0x00BEAE49]\n\t(No symbol) [0x00BD1C96]\n\t(No symbol) [0x00BA3FAC]\n\t(No symbol) [0x00BA4F3D]\n\tGetHandleVerifier [0x00FF5543+3113795]\n\tGetHandleVerifier [0x0100A20A+3198986]\n\tGetHandleVerifier [0x010029E2+3168226]\n\tGetHandleVerifier [0x00DA3250+680016]\n\t(No symbol) [0x00C9572D]\n\t(No symbol) [0x00C929D8]\n\t(No symbol) [0x00C92B75]\n\t(No symbol) [0x00C857D0]\n\tBaseThreadInitThunk [0x757D7BA9+25]\n\tRtlInitializeExceptionChain [0x7784C0CB+107]\n\tRtlClearBits [0x7784C04F+191]\n\n", "trace": "  File \"C:\\Users\\sarab\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\pluggy\\_callers.py\", line 77, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\sarab\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\_pytest\\fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\sarab\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\_pytest\\fixtures.py\", line 902, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"C:\\Users\\sarab\\Downloads\\MyKareer\\login\\test_login.py\", line 30, in setup_login\n    lp.click_login_lp()\n  File \"C:\\Users\\sarab\\Downloads\\MyKareer\\login\\page.py\", line 14, in click_login_lp\n    self.click_element('CSS_SELECTOR', landing_page.login_css)\n  File \"C:\\Users\\sarab\\Downloads\\MyKareer\\helpers\\base_page.py\", line 56, in click_element\n    element = WebDriverWait(self.driver, timeout).until(\n  File \"C:\\Users\\sarab\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 96, in until\n    value = method(self._driver)\n  File \"C:\\Users\\sarab\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\selenium\\webdriver\\support\\expected_conditions.py\", line 363, in _predicate\n    target = driver.find_element(*target)  # grab element at locator\n  File \"C:\\Users\\sarab\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 766, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n  File \"C:\\Users\\sarab\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 380, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\sarab\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1732445551384, "stop": 1732445556246}], "start": 1732445551384, "stop": 1732445556350}